# Use the node image from official Docker Hub
FROM node:20.14.0-alpine3.20

# Set the working directory inside the container
WORKDIR /app

# Install bash
RUN apk add --no-cache bash

# Copy package.json and yarn.lock to install dependencies
COPY frontend/package.json frontend/yarn.lock* ./

# Install project dependencies
RUN yarn install

# Copy the rest of the project files to the container
COPY frontend/ .

# Expose port 3000 (or the port your Vite server uses)
EXPOSE 3000

# Start the Vite development server explicitly on port 3000
CMD ["yarn", "dev", "--port", "3000"]
