version: "3.8"

services:
  laravel.test:
    build:
      context: ./backend/vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: laravel/authentication
    container_name: laravelAuthentication
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
    volumes:
      - "./backend:/var/www/html"
    networks:
      - sail
    depends_on:
      - selenium
      - pgsql
      - phppgadmin

  selenium:
    # for windows and linux
    # image: selenium/standalone-chrome
    # for mac containing Apple Silicon chip
    image: "seleniarm/standalone-chromium"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - sail

  pgsql:
    image: "postgres:15"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
      - "sail-pgsql:/var/lib/postgresql/data"
      - "./backend/vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "${DB_DATABASE}"
        - "-U"
        - "${DB_USERNAME}"
      retries: 3
      timeout: 5s

  phppgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8087:80"
    depends_on:
      - pgsql
    networks:
      - sail
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
      - ./setup_pgadmin.sh:/docker-entrypoint-initdb.d/setup_pgadmin.sh

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vueCognito
    ports:
      - 8081:80

  nginx:
    image: nginx:alpine
    container_name: vue-cognito-nginx-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    depends_on:
      - app
networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
  pgadmin-data:
    driver: local
