export class TextHelper {
  static loginPageCardHeader = 'Sign in to our platform'
  static loginSubmitButtonText = 'Login to your account'
  static loginYourEmail = 'Your email'
  static loginYourPassword = 'Your password'
  static loginRememberMe = 'Remember me'
  static loginForgotPassword = 'Forgot Password?'
  static loginNotRegistered = 'Not registered?'
  static loginCreateAccount = 'Create account'
  static registerCardHeader = 'Sign up to our platform'
  static registerFullName = 'Full name'
  static registerYourEmail = 'Your email'
  static registerYourPassword = 'Your password'
  static registerTerms = 'Terms and Conditions'
  static registerPolicy = 'Privacy Policies'
  static registerSubmitButtonText = 'Register to our platform'
  static registerAlreadyAccount = 'Already has an account?'
  static registerLogin = 'Login'
  static verificationCardHeader = 'Verify Email Address'
  static verificationNote =
    "Before getting started, could you verify your email address by entering the verification pin we just emailed to you? If you didn't receive the email, we will gladly send you another."
  static verificationVerificationPin = 'Verification Pin'
  static verificationNoPin = "Didn't get a pin?"
  static verificationResend = 'Resend'
  static verificationSubmitButonText = 'Verify'
  static verificationBackLink = 'Back to login'
  static forgotCardHeader = 'Forgot Password'
  static forgotNote =
    'Forgot your password? No problem. Just let us know your email address and we will email you a password reset pin that will allow you to choose a new one.'
  static forgotYourEmail = 'Your email'
  static forgotSubmitButtonText = 'Search'
  static forgotBackLink = 'Back to login'
  static resetCardHeader = 'Change Your Password'
  static resetYourEmail = 'Your email'
  static resetVerificationPin = 'Verification pin'
  static resetNewPassword = 'New password'
  static resetSubmitButtonText = 'Change Password'
  static resetBackLink = 'Back to login'
}
